name: Arduino CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get arduino-cli 0.10.0 release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "arduino/arduino-cli"
          version: "tags/0.10.0"
          file: "arduino-cli_0.10.0_Linux_64bit.tar.gz"
      
      - name: Extract arduino-cli release
        run: |
          tar -xf arduino-cli_0.10.0_Linux_64bit.tar.gz
        
      - name: Add execute permission to arduino-cli
        run: chmod +x arduino-cli
      
      - name: Install arduino avr core
        run: |
          ./arduino-cli core update-index
          ./arduino-cli core install arduino:avr
      
      - name: Install FastLED library
        run: |
          ./arduino-cli lib install fastled
      
      - name: Compile
        run: |
          mkdir -p lights/build
          ./arduino-cli compile -b arduino:avr:mega --build-path "/home/runner/work/truckleds/truckleds/lights/build/" ./lights/lights.cpp
